customOpen:
    "1": "1"
    q: q
    s: s
    x: x
    啊啊: 啊啊
    啥啥啥: 啥啥啥
downloadDir: ""
downloadNoticeEnable: "on"
downloadNoticeText: ""
downloadVoiceEnable: "on"
downloadVoiceText: 啥啥啥
memoHost: ""
memoToken: ""
nickName: ""
proxy: ""
proxyIgnore: ""
resource: ""
uploadMinio:
    access: 实时
    bucket: 实时
    endpoint: ""
    rename: false
    secret: 实时
